# Generated by Django 4.2.1 on 2023-12-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Requests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=255)),
                ("text", models.CharField(max_length=255)),
                ("headers", models.JSONField()),
                ("time_create", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
