# Generated by Django 4.2.1 on 2023-12-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("string_script", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requests",
            name="headers",
            field=models.TextField(),
        ),
    ]
